external_components:
  - source:
      type: git
      url: https://github.com/scholzri/esphome-standing-desk
      ref: master
    components: [ standing_desk_height, desk_keypad ]
    refresh: 0s

substitutions:
  desk_height_name: "Desk Height"
  target_desk_height_name: "Target Desk Height"
  standing_desk_height_units: "cm"
  standing_desk_variant: "auto"

sensor:
  - uart_id: standing_desk_uart
    platform: standing_desk_height
    id: desk_height
    name: ${desk_height_name}
    unit_of_measurement: ${standing_desk_height_units}
    variant: ${standing_desk_variant}

substitutions:
  desk_height_name: "Desk Height"
  target_desk_height_name: "Target Desk Height"
  standing_desk_height_units: "in"
  standing_desk_variant: "auto"

sensor:
  - platform: standing_desk_height
    uart_id: controlbox
    id: desk_height
    name: ${desk_height_name}
    unit_of_measurement: ${standing_desk_height_units}
    variant: ${standing_desk_variant}

number:
  - platform: template
    id: target_desk_height
    name: ${target_desk_height_name}
    unit_of_measurement: ${standing_desk_height_units}
    restore_value: true
    optimistic: true
    min_value: ${standing_desk_min_height}
    max_value: ${standing_desk_max_height}
    step: 0.1
    set_action:
      then:
        - desk_keypad.move_to_target:
            id: desk_keypad_control
            target: !lambda "return x;"
